### PR TITLE
add nahraway evaluator

### LINKED ISSUE #65: Nahrawy image classification
https://huggingface.co/Nahrawy/AIorNot implement this

### PR DESCRIPTION
**Pull request by LeviUniAcc**
@1Maxnet1 @EhrenbruderRoschtbraten

### CODE REVIEW

**Review by 1Maxnet1 — APPROVED** [review]
Looks good to me, thanks for implementing.

**Review by RaphaW — COMMENTED** [review]
When testing this warning appeared.
image
Could you please try to remove it. Then it looks very good. Thanks

**Review by 1Maxnet1 — APPROVED** [review]
LGTM

**Review by RaphaW — APPROVED** [review]
Apart from the warning it already looked good

**Review by EhrenbruderRoschtbraten — APPROVED** [review]
One small change that could be addressed, otherwise its fine

**Pull request merged**
